services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=main_db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my_network

  all-in-one:
    container_name: all-in-one
    build:
      context: .
      dockerfile: docker_files/Dockerfile
    command: tail -f /dev/null
    networks:
      - my_network


networks:
  my_network:
  external_network:
    external: true

volumes:
  data: